// גנרטור טבלאות הנתונים של כלי "תיקון קוראים".
// טוען את קבצי ה-JS של התוסף המקורי ופולט אותם כ-const דארט.
//   node tool/tikkun_korim/generate_data.mjs [outDir]
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { loadPluginScripts } from './js_env.mjs';
import { applyReadingsOverrides } from './overrides/readings.mjs';
import { applyHaftarotOverrides } from './overrides/haftarot.mjs';

const OUT = path.resolve(process.argv[2] ?? 'lib/tools/tikkun_korim/data');
const HEADER =
  '// generated by tool/tikkun_korim/generate_data.mjs — do not edit\n' +
  '// ignore_for_file: prefer_single_quotes\n\n';

const ctx = loadPluginScripts([
  'tanach_structure.js',
  'parasha_index.js',
  'torah_layouts.js',
  'aliyot_index.js',
  'haftarot_index.js',
  'torah_readings_index.js',
  'special_layouts.js',
]);

const get = (expr) => vm.runInContext(expr, ctx);

function dartString(s) {
  let out = "'";
  for (const ch of s) {
    const code = ch.codePointAt(0);
    if (ch === '\\') out += '\\\\';
    else if (ch === "'") out += "\\'";
    else if (ch === '$') out += '\\$';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\r') out += '\\r';
    else if (ch === '\t') out += '\\t';
    else if (code < 0x20 || code === 0x7f) out += '\\u' + code.toString(16).padStart(4, '0');
    else if (code >= 0xe000 && code <= 0xf8ff) out += '\\u' + code.toString(16).toUpperCase().padStart(4, '0');
    else out += ch;
  }
  return out + "'";
}

function dartValue(v, indent) {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'string') return dartString(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') {
    if (!Number.isFinite(v)) throw new Error('non-finite number');
    return Number.isInteger(v) ? String(v) : String(v);
  }
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    const parts = v.map((x) => padIn + dartValue(x, indent + 1));
    return '[\n' + parts.join(',\n') + ',\n' + pad + ']';
  }
  if (typeof v === 'object') {
    const keys = Object.keys(v).filter((k) => typeof v[k] !== 'function');
    if (keys.length === 0) return '<String, Object?>{}';
    const parts = keys.map((k) => padIn + dartString(k) + ': ' + dartValue(v[k], indent + 1));
    return '{\n' + parts.join(',\n') + ',\n' + pad + '}';
  }
  throw new Error('unsupported value type: ' + typeof v);
}

function emit(file, decls) {
  let body = HEADER;
  for (const [type, name, value] of decls) {
    body += `const ${type} ${name} = ${dartValue(value, 0)};\n\n`;
  }
  fs.mkdirSync(OUT, { recursive: true });
  const target = path.join(OUT, file);
  fs.writeFileSync(target, body);
  console.log(`${file}: ${body.length} bytes`);
}

const M = 'Map<String, Object?>';
const L = 'List<Object?>';

// תיקוני נתונים שאינם במקור ה-JS. ראש חצי-השיטה בשירת האזינו לפי רשימת
// הרמב"ם (הל' ס"ת ח, ד) הוא "בני בשן", ולא המילה שלפניה.
const SPECIAL_SECTION_FIXES = {
  shirat_haazinu: {
    extraBreaks: [[['חלב', 'כרים'], ['כרים', 'ואילים']]],
  },
};

function specialSections() {
  const sections = get('JSON.parse(JSON.stringify(SPECIAL_SECTIONS))');
  for (const [id, fixes] of Object.entries(SPECIAL_SECTION_FIXES)) {
    const sec = sections.find((s) => s.id === id);
    if (!sec) throw new Error(`special section not found: ${id}`);
    for (const [field, replacements] of Object.entries(fixes)) {
      for (const [from, to] of replacements) {
        const idx = (sec[field] ?? []).findIndex(
          (p) => p.length === from.length && p.every((w, i) => w === from[i]),
        );
        if (idx < 0) throw new Error(`${id}.${field}: pattern not found: ${from}`);
        sec[field][idx] = to;
      }
    }
  }
  return sections;
}

emit('torah_layouts.g.dart', [[M, 'kTorahLayouts', get('TORAH_LAYOUTS')]]);
emit('special_sections.g.dart', [[L, 'kSpecialSections', specialSections()]]);
emit('haftarot_index.g.dart', [[L, 'kHaftarotList', applyHaftarotOverrides(get('HAFTAROT_LIST'))]]);
emit('torah_readings_index.g.dart', [
  [L, 'kTorahReadingsList', applyReadingsOverrides(get('TORAH_READINGS_LIST'))],
  ['Map<String, String>', 'kTorahReadingsCategories', get('TORAH_READINGS_CATEGORIES')],
]);
emit('parasha_index.g.dart', [
  [M, 'kParashaOpenings', get('PARASHA_OPENINGS')],
  ['List<String>', 'kAllParashotOrder', get('ALL_PARASHOT_ORDER')],
]);

// TORAH_STRUCTURE / BOOKS_ORDER / PARASHA_NAME_MAPPING יושבים ב-navigation.js,
// שנשען על ה-DOM בעת הטעינה; מחלצים אותם משם בהרצה נפרדת עם אותו shim.
const navCtx = loadPluginScripts([
  'tanach_structure.js',
  'parasha_index.js',
  'torah_layouts.js',
  'aliyot_index.js',
  'haftarot_index.js',
  'torah_readings_index.js',
  'special_layouts.js',
  'page_layout_engine.js',
  'navigation.js',
]);
const navGet = (expr) => vm.runInContext(expr, navCtx);

emit('tanach_structure.g.dart', [
  [M, 'kTorahStructure', navGet('TORAH_STRUCTURE')],
  ['List<String>', 'kBooksOrder', navGet('BOOKS_ORDER')],
  ['Map<String, String>', 'kParashaNameMapping', navGet('PARASHA_NAME_MAPPING')],
  [L, 'kTanachNeviim', navGet('TANACH_NEVIIM')],
  [L, 'kTanachKetuvim', navGet('TANACH_KETUVIM')],
  ['Map<String, String>', 'kAliyaDisplayNames', navGet('ALIYA_DISPLAY_NAMES')],
  [M, 'kCombinedParashaMap', navGet('COMBINED_PARASHA_MAP')],
]);

// --- אינדקס העליות: טווחי פסוקים מ-@hebcal/leyning ---
// חמש מילות הפתיחה של התוסף אינן מזהות עליה ביחידות; המקור כאן הוא
// `aliyot.json` של החבילה — נתיב חלופי דרך TIKKUN_HEBCAL_ALIYOT.
const HEBCAL_ALIYOT =
  process.env.TIKKUN_HEBCAL_ALIYOT ??
  'node_modules/@hebcal/leyning/dist/esm/aliyot.json.js';

function loadHebcalAliyot() {
  let src = fs.readFileSync(path.resolve(HEBCAL_ALIYOT), 'utf8');
  src = src
    .replace(/^﻿/, '')
    .replace(/^\s*export\s+default\s*/, '')
    .replace(/^\/\/# sourceMappingURL=.*$/m, '')
    .trim();
  if (src.endsWith(';')) src = src.slice(0, -1);
  return JSON.parse(src);
}

const ALIYA_ORDER = ['1', '2', '3', '4', '5', '6', '7', 'M'];
const ALIYA_KEY_NAMES = {
  1: 'עליה א', 2: 'עליה ב', 3: 'עליה ג', 4: 'עליה ד',
  5: 'עליה ה', 6: 'עליה ו', 7: 'עליה ז', M: 'מפטיר',
};

function aliyaEntries(src) {
  const out = [];
  for (const key of ALIYA_ORDER) {
    const v = src?.[key];
    if (!v) continue;
    const entry = { aliya: ALIYA_KEY_NAMES[key], from: v[0], to: v[1] };
    // ההערה היחידה ב-hebcal היא חלופת חלוקה; נשמרת כטווח, לא כטקסט אנגלי.
    const alt = v[2] && /^some sources use /.test(v[2])
      ? v[2].match(/^some sources use (\d+):(\d+)-(?:(\d+):)?(\d+)$/)
      : null;
    if (v[2] && !alt) throw new Error(`unhandled aliyot note: ${v[2]}`);
    if (alt) {
      entry.altFrom = `${alt[1]}:${alt[2]}`;
      entry.altTo = `${alt[3] ?? alt[1]}:${alt[4]}`;
    }
    out.push(entry);
  }
  return out;
}

function buildAliyotDecls() {
  const raw = loadHebcalAliyot();
  const structure = navGet('TORAH_STRUCTURE');
  const booksOrder = navGet('BOOKS_ORDER');
  const order = get('ALL_PARASHOT_ORDER');
  // PARASHA_NAME_MAPPING הוא תצוגה→מנורמל; האינדקס נשמר בשמות התצוגה.
  const displayOf = new Map(
    Object.entries(navGet('PARASHA_NAME_MAPPING')).map(([d, n]) => [n, d]),
  );
  const heByNum = (n) => displayOf.get(order[n - 1]) ?? order[n - 1];

  const byParasha = new Map();
  const combinedAfter = new Map();
  for (const src of Object.values(raw)) {
    const bookName = structure[booksOrder[src.book - 1]].name;
    const name = src.combined
      ? `${heByNum(src.num1)}-${heByNum(src.num2)}`
      : heByNum(src.num);
    byParasha.set(name, { bookName, src });
    if (src.combined) combinedAfter.set(heByNum(src.num2), name);
  }

  const full = {};
  const weekday = {};
  for (const bookId of booksOrder) {
    const bookName = structure[bookId].name;
    full[bookName] = {};
    weekday[bookName] = {};
    for (const parasha of structure[bookId].parashot) {
      for (const name of [parasha, combinedAfter.get(parasha)]) {
        if (!name) continue;
        const found = byParasha.get(name);
        if (!found) throw new Error(`missing hebcal aliyot for ${name}`);
        if (found.bookName !== bookName) {
          throw new Error(`book mismatch for ${name}`);
        }
        full[bookName][name] = aliyaEntries(found.src.fullkriyah);
        const wd = aliyaEntries(found.src.weekday);
        if (wd.length > 0) weekday[bookName][name] = wd;
      }
    }
  }
  return [
    [M, 'kAliyotIndex', full],
    [M, 'kWeekdayAliyotIndex', weekday],
  ];
}

emit('aliyot_index.g.dart', buildAliyotDecls());

// --- טעם עליון / טעם תחתון לעשרת הדברות ---
// המקור: bdenckla/MAM-basics, out/mam-decnreub.json. ראה vendor/PROVENANCE.md.
// מיפוי מספור MAM → מספור המסד: המסד (Sefaria) מפצל את הדיבר הראשון לשניים
// ואינו מפצל את הדברות הקצרות; מתועד ב-MAM-simple/doc/versification-differences.md.
const DECALOGUE_PLACES = [
  { book: 'שמות', prefix: 'E20:', chapter: 20, splitVerse: 2, fromVerse: 2, toVerse: 14 },
  { book: 'דברים', prefix: 'D5:', chapter: 5, splitVerse: 6, fromVerse: 6, toVerse: 18 },
];

const SEP = /[־\s]+/;
// השוואה על העיצורים בלבד: CGJ (U+034F) בא רק בצורה המשולבת,
// שבה הוא שומר על סדר הטעמים משתי המערכות.
const stripTeamim = (s) => s.replace(/[֑-ׇ͏]/g, '');
// cleanRawText מנרמל קמץ קטן לקמץ; בלי אותו נרמול המילה
// המוחלפת לא תזוהה מול המסד.
const normalizeTaamWord = (s) => s.replace(/ׇ/g, 'ָ');

function buildDecalogueDecl() {
  const src = path.resolve('tool/tikkun_korim/vendor/mam-decnreub.json');
  const raw = JSON.parse(fs.readFileSync(src, 'utf8'));
  const out = {};
  for (const place of DECALOGUE_PLACES) {
    const words = [];
    for (const e of raw) {
      if (!e.bcv.startsWith(place.prefix)) continue;
      // רשומה שאינה מחרוזת היא תבנית פרשה/פסק של הוויקיטקסט, לא מילה.
      if (typeof e.wco !== 'string') continue;
      const merged = normalizeTaamWord(e.wco);
      const elyon = normalizeTaamWord(e.wup);
      const tachton = normalizeTaamWord(e.wlo);
      // מקף/רווח נחלקים אחרת בין שתי המערכות; ההשוואה היא על העיצורים בלבד.
      const parts = (w) => stripTeamim(w).split(SEP).filter(Boolean);
      const skeleton = parts(merged);
      for (const other of [elyon, tachton]) {
        const p = parts(other);
        if (p.length !== skeleton.length || p.some((x, k) => x !== skeleton[k])) {
          throw new Error(`decalogue: consonants differ at ${e.bcv}`);
        }
      }
      const prev = words[words.length - 1];
      // המקור מביא את אותה מילה פעמיים כשיש בה קמץ קטן; אחרי הנרמול הן זהות.
      if (prev && prev.merged === merged && prev.elyon === elyon && prev.tachton === tachton) {
        continue;
      }
      const mamVerse = Number(e.bcv.slice(place.prefix.length));
      const vFrom = mamVerse === place.splitVerse ? mamVerse : mamVerse + 1;
      words.push({ vFrom, vTo: mamVerse + 1, merged, elyon, tachton });
    }
    if (words.length === 0) throw new Error(`decalogue: no words for ${place.book}`);
    out[place.book] = {
      chapter: place.chapter,
      fromVerse: place.fromVerse,
      toVerse: place.toVerse,
      words,
    };
  }
  return [[M, 'kDecalogueTaamim', out]];
}

emit('decalogue_taamim.g.dart', buildDecalogueDecl());
