// generated by tool/tikkun_korim/generate_data.mjs — do not edit
// ignore_for_file: prefer_single_quotes

const List<Object?> kHaftarotList = [
  {
    'id': 'p:Bereshit',
    'category': 'parasha',
    'name': 'בראשית',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '42:5',
        'to': '43:10',
      },
    ],
    'sephard': [
      {
        'book': 'ישעיהו',
        'from': '42:5',
        'to': '42:21',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Noach',
    'category': 'parasha',
    'name': 'נח',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '54:1',
        'to': '55:5',
      },
    ],
    'sephard': [
      {
        'book': 'ישעיהו',
        'from': '54:1',
        'to': '54:10',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Lech-Lecha',
    'category': 'parasha',
    'name': 'לך לך',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '40:27',
        'to': '41:16',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vayera',
    'category': 'parasha',
    'name': 'וירא',
    'ashkenaz': [
      {
        'book': 'מלכים ב',
        'from': '4:1',
        'to': '4:37',
      },
    ],
    'sephard': [
      {
        'book': 'מלכים ב',
        'from': '4:1',
        'to': '4:23',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Chayei Sara',
    'category': 'parasha',
    'name': 'חיי שרה',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '1:1',
        'to': '1:31',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Toldot',
    'category': 'parasha',
    'name': 'תולדות',
    'ashkenaz': [
      {
        'book': 'מלאכי',
        'from': '1:1',
        'to': '2:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vayetzei',
    'category': 'parasha',
    'name': 'ויצא',
    'ashkenaz': [
      {
        'book': 'הושע',
        'from': '12:13',
        'to': '14:10',
      },
    ],
    'sephard': [
      {
        'book': 'הושע',
        'from': '11:7',
        'to': '12:12',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Vayishlach',
    'category': 'parasha',
    'name': 'וישלח',
    'ashkenaz': [
      {
        'book': 'עובדיה',
        'from': '1:1',
        'to': '1:21',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vayeshev',
    'category': 'parasha',
    'name': 'וישב',
    'ashkenaz': [
      {
        'book': 'עמוס',
        'from': '2:6',
        'to': '3:8',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Miketz',
    'category': 'parasha',
    'name': 'מקץ',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '3:15',
        'to': '4:1',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vayigash',
    'category': 'parasha',
    'name': 'ויגש',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '37:15',
        'to': '37:28',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vayechi',
    'category': 'parasha',
    'name': 'ויחי',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '2:1',
        'to': '2:12',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Shemot',
    'category': 'parasha',
    'name': 'שמות',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '27:6',
        'to': '28:13',
      },
      {
        'book': 'ישעיהו',
        'from': '29:22',
        'to': '29:23',
      },
    ],
    'sephard': [
      {
        'book': 'ירמיהו',
        'from': '1:1',
        'to': '2:3',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Vaera',
    'category': 'parasha',
    'name': 'וארא',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '28:25',
        'to': '29:21',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Bo',
    'category': 'parasha',
    'name': 'בא',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '46:13',
        'to': '46:28',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Beshalach',
    'category': 'parasha',
    'name': 'בשלח',
    'ashkenaz': [
      {
        'book': 'שופטים',
        'from': '4:4',
        'to': '5:31',
      },
    ],
    'sephard': [
      {
        'book': 'שופטים',
        'from': '5:1',
        'to': '5:31',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Yitro',
    'category': 'parasha',
    'name': 'יתרו',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '6:1',
        'to': '7:6',
      },
      {
        'book': 'ישעיהו',
        'from': '9:5',
        'to': '9:6',
      },
    ],
    'sephard': [
      {
        'book': 'ישעיהו',
        'from': '6:1',
        'to': '6:13',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Mishpatim',
    'category': 'parasha',
    'name': 'משפטים',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '34:8',
        'to': '34:22',
      },
      {
        'book': 'ירמיהו',
        'from': '33:25',
        'to': '33:26',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Terumah',
    'category': 'parasha',
    'name': 'תרומה',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '5:26',
        'to': '6:13',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Tetzaveh',
    'category': 'parasha',
    'name': 'תצוה',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '43:10',
        'to': '43:27',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Ki Tisa',
    'category': 'parasha',
    'name': 'כי תשא',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '18:1',
        'to': '18:39',
      },
    ],
    'sephard': [
      {
        'book': 'מלכים א',
        'from': '18:20',
        'to': '18:39',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Vayakhel',
    'category': 'parasha',
    'name': 'ויקהל',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '7:40',
        'to': '7:50',
      },
    ],
    'sephard': [
      {
        'book': 'מלכים א',
        'from': '7:13',
        'to': '7:26',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Pekudei',
    'category': 'parasha',
    'name': 'פקודי',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '7:51',
        'to': '8:21',
      },
    ],
    'sephard': [
      {
        'book': 'מלכים א',
        'from': '7:40',
        'to': '7:50',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Vayakhel-Pekudei',
    'category': 'parasha',
    'name': 'ויקהל-פקודי',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '7:51',
        'to': '8:21',
      },
    ],
    'sephard': [
      {
        'book': 'מלכים א',
        'from': '7:40',
        'to': '7:50',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Vayikra',
    'category': 'parasha',
    'name': 'ויקרא',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '43:21',
        'to': '44:23',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Tzav',
    'category': 'parasha',
    'name': 'צו',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '7:21',
        'to': '8:3',
      },
      {
        'book': 'ירמיהו',
        'from': '9:22',
        'to': '9:23',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Shmini',
    'category': 'parasha',
    'name': 'שמיני',
    'ashkenaz': [
      {
        'book': 'שמואל ב',
        'from': '6:1',
        'to': '7:17',
      },
    ],
    'sephard': [
      {
        'book': 'שמואל ב',
        'from': '6:1',
        'to': '6:19',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Tazria',
    'category': 'parasha',
    'name': 'תזריע',
    'ashkenaz': [
      {
        'book': 'מלכים ב',
        'from': '4:42',
        'to': '5:19',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Metzora',
    'category': 'parasha',
    'name': 'מצורע',
    'ashkenaz': [
      {
        'book': 'מלכים ב',
        'from': '7:3',
        'to': '7:20',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Tazria-Metzora',
    'category': 'parasha',
    'name': 'תזריע-מצורע',
    'ashkenaz': [
      {
        'book': 'מלכים ב',
        'from': '7:3',
        'to': '7:20',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Achrei Mot',
    'category': 'parasha',
    'name': 'אחרי מות',
    'ashkenaz': [
      {
        'book': 'עמוס',
        'from': '9:7',
        'to': '9:15',
      },
    ],
    'sephard': [
      {
        'book': 'יחזקאל',
        'from': '22:1',
        'to': '22:16',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Kedoshim',
    'category': 'parasha',
    'name': 'קדושים (יש הקוראים עד כב, טז)',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '22:1',
        'to': '22:19',
      },
    ],
    'sephard': [
      {
        'book': 'יחזקאל',
        'from': '20:2',
        'to': '20:20',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Achrei Mot-Kedoshim',
    'category': 'parasha',
    'name': 'אחרי מות-קדושים',
    'ashkenaz': [
      {
        'book': 'עמוס',
        'from': '9:7',
        'to': '9:15',
      },
    ],
    'sephard': [
      {
        'book': 'יחזקאל',
        'from': '20:2',
        'to': '20:20',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Emor',
    'category': 'parasha',
    'name': 'אמור',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '44:15',
        'to': '44:31',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Behar',
    'category': 'parasha',
    'name': 'בהר',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '32:6',
        'to': '32:27',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Bechukotai',
    'category': 'parasha',
    'name': 'בחוקותי',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '16:19',
        'to': '17:14',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Behar-Bechukotai',
    'category': 'parasha',
    'name': 'בהר-בחוקותי',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '16:19',
        'to': '17:14',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Bamidbar',
    'category': 'parasha',
    'name': 'במדבר',
    'ashkenaz': [
      {
        'book': 'הושע',
        'from': '2:1',
        'to': '2:22',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Nasso',
    'category': 'parasha',
    'name': 'נשא',
    'ashkenaz': [
      {
        'book': 'שופטים',
        'from': '13:2',
        'to': '13:25',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Beha\'alotcha',
    'category': 'parasha',
    'name': 'בהעלותך',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Sh\'lach',
    'category': 'parasha',
    'name': 'שלח לך',
    'ashkenaz': [
      {
        'book': 'יהושע',
        'from': '2:1',
        'to': '2:24',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Korach',
    'category': 'parasha',
    'name': 'קרח',
    'ashkenaz': [
      {
        'book': 'שמואל א',
        'from': '11:14',
        'to': '12:22',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Chukat',
    'category': 'parasha',
    'name': 'חקת',
    'ashkenaz': [
      {
        'book': 'שופטים',
        'from': '11:1',
        'to': '11:33',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Balak',
    'category': 'parasha',
    'name': 'בלק',
    'ashkenaz': [
      {
        'book': 'מיכה',
        'from': '5:6',
        'to': '6:8',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Chukat-Balak',
    'category': 'parasha',
    'name': 'חקת-בלק',
    'ashkenaz': [
      {
        'book': 'מיכה',
        'from': '5:6',
        'to': '6:8',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Pinchas',
    'category': 'parasha',
    'name': 'פנחס',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '18:46',
        'to': '19:21',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Matot',
    'category': 'parasha',
    'name': 'מטות',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '1:1',
        'to': '2:3',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Masei',
    'category': 'parasha',
    'name': 'מסעי',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '2:4',
        'to': '2:28',
      },
      {
        'book': 'ירמיהו',
        'from': '3:4',
        'to': '3:4',
      },
    ],
    'sephard': [
      {
        'book': 'ירמיהו',
        'from': '2:4',
        'to': '2:28',
      },
      {
        'book': 'ירמיהו',
        'from': '4:1',
        'to': '4:2',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Matot-Masei',
    'category': 'parasha',
    'name': 'מטות-מסעי',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '2:4',
        'to': '2:28',
      },
      {
        'book': 'ירמיהו',
        'from': '3:4',
        'to': '3:4',
      },
    ],
    'sephard': [
      {
        'book': 'ירמיהו',
        'from': '2:4',
        'to': '2:28',
      },
      {
        'book': 'ירמיהו',
        'from': '4:1',
        'to': '4:2',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'p:Devarim',
    'category': 'parasha',
    'name': 'דברים',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '1:1',
        'to': '1:27',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vaetchanan',
    'category': 'parasha',
    'name': 'ואתחנן',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '40:1',
        'to': '40:26',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Eikev',
    'category': 'parasha',
    'name': 'עקב',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '49:14',
        'to': '51:3',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Re\'eh',
    'category': 'parasha',
    'name': 'ראה',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '54:11',
        'to': '55:5',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Shoftim',
    'category': 'parasha',
    'name': 'שופטים',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '51:12',
        'to': '52:12',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Ki Teitzei',
    'category': 'parasha',
    'name': 'כי תצא',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '54:1',
        'to': '54:10',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Ki Tavo',
    'category': 'parasha',
    'name': 'כי תבוא',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '60:1',
        'to': '60:22',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Nitzavim',
    'category': 'parasha',
    'name': 'נצבים',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '61:10',
        'to': '63:9',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vayeilech',
    'category': 'parasha',
    'name': 'וילך',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '55:6',
        'to': '56:8',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Nitzavim-Vayeilech',
    'category': 'parasha',
    'name': 'נצבים-וילך',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '61:10',
        'to': '63:9',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Ha\'azinu',
    'category': 'parasha',
    'name': 'האזינו',
    'ashkenaz': [
      {
        'book': 'שמואל ב',
        'from': '22:1',
        'to': '22:51',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'p:Vezot Haberakhah',
    'category': 'parasha',
    'name': 'וזאת הברכה',
    'ashkenaz': [
      {
        'book': 'יהושע',
        'from': '1:1',
        'to': '1:18',
      },
    ],
    'sephard': [
      {
        'book': 'יהושע',
        'from': '1:1',
        'to': '1:9',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Pesach I',
    'category': 'special',
    'name': 'פסח - יום ראשון',
    'ashkenaz': [
      {
        'book': 'יהושע',
        'from': '3:5',
        'to': '3:7',
      },
      {
        'book': 'יהושע',
        'from': '5:2',
        'to': '6:1',
      },
      {
        'book': 'יהושע',
        'from': '6:27',
        'to': '6:27',
      },
    ],
    'sephard': [
      {
        'book': 'יהושע',
        'from': '5:2',
        'to': '6:1',
      },
      {
        'book': 'יהושע',
        'from': '6:27',
        'to': '6:27',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Pesach II',
    'category': 'special',
    'name': 'פסח - יום שני (חו"ל)',
    'ashkenaz': [
      {
        'book': 'מלכים ב',
        'from': '23:1',
        'to': '23:9',
      },
      {
        'book': 'מלכים ב',
        'from': '23:21',
        'to': '23:25',
      },
    ],
    'sephard': [],
    'land': 'diaspora',
  },
  {
    'id': 'h:Pesach Shabbat Chol ha-Moed',
    'category': 'special',
    'name': 'פסח - שבת חול המועד',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '37:1',
        'to': '37:14',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Pesach VII',
    'category': 'special',
    'name': 'פסח - שביעי של פסח',
    'ashkenaz': [
      {
        'book': 'שמואל ב',
        'from': '22:1',
        'to': '22:51',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Pesach VIII',
    'category': 'special',
    'name': 'פסח - אחרון של פסח (חו"ל)',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '10:32',
        'to': '12:6',
      },
    ],
    'sephard': [],
    'land': 'diaspora',
  },
  {
    'id': 'h:Shavuot I',
    'category': 'special',
    'name': 'שבועות - יום ראשון',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '1:1',
        'to': '1:28',
      },
      {
        'book': 'יחזקאל',
        'from': '3:12',
        'to': '3:12',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Shavuot II',
    'category': 'special',
    'name': 'שבועות - יום שני (חו"ל)',
    'ashkenaz': [
      {
        'book': 'חבקוק',
        'from': '3:1',
        'to': '3:19',
      },
    ],
    'sephard': [
      {
        'book': 'חבקוק',
        'from': '2:20',
        'to': '3:19',
      },
    ],
    'land': 'diaspora',
  },
  {
    'id': 'h:Tish\'a B\'Av',
    'category': 'special',
    'name': 'תשעה באב - שחרית',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '8:13',
        'to': '9:23',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Tish\'a B\'Av (Mincha)',
    'category': 'special',
    'name': 'תשעה באב - מנחה',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '55:6',
        'to': '56:8',
      },
    ],
    'sephard': [
      {
        'book': 'הושע',
        'from': '14:2',
        'to': '14:10',
      },
      {
        'book': 'מיכה',
        'from': '7:18',
        'to': '7:20',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Fast Day (Afternoon)',
    'category': 'special',
    'name': 'תענית - מנחה',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '55:6',
        'to': '56:8',
      },
    ],
    'sephard': [],
    'sephardNone': true,
    'land': 'both',
  },
  {
    'id': 'h:Rosh Hashana I',
    'category': 'special',
    'name': 'ראש השנה - יום ראשון',
    'ashkenaz': [
      {
        'book': 'שמואל א',
        'from': '1:1',
        'to': '2:10',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Rosh Hashana II',
    'category': 'special',
    'name': 'ראש השנה - יום שני',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '31:2',
        'to': '31:20',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Yom Kippur',
    'category': 'special',
    'name': 'יום כיפור - שחרית',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '57:14',
        'to': '58:14',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Yom Kippur (Mincha)',
    'category': 'special',
    'name': 'יום כיפור - מנחה',
    'ashkenaz': [
      {
        'book': 'יונה',
        'from': '1:1',
        'to': '4:11',
      },
      {
        'book': 'מיכה',
        'from': '7:18',
        'to': '7:20',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Sukkot I',
    'category': 'special',
    'name': 'סוכות - יום ראשון',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '14:1',
        'to': '14:21',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Sukkot II',
    'category': 'special',
    'name': 'סוכות - יום שני (חו"ל)',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '8:2',
        'to': '8:21',
      },
    ],
    'sephard': [],
    'land': 'diaspora',
  },
  {
    'id': 'h:Sukkot Shabbat Chol ha-Moed',
    'category': 'special',
    'name': 'סוכות - שבת חול המועד',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '38:18',
        'to': '39:16',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Shmini Atzeret',
    'category': 'special',
    'name': 'שמיני עצרת',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '8:54',
        'to': '8:66',
      },
    ],
    'sephard': [],
    'land': 'diaspora',
  },
  {
    'id': 'h:Simchat Torah',
    'category': 'special',
    'name': 'שמחת תורה',
    'ashkenaz': [
      {
        'book': 'יהושע',
        'from': '1:1',
        'to': '1:18',
      },
    ],
    'sephard': [
      {
        'book': 'יהושע',
        'from': '1:1',
        'to': '1:9',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Rosh Chodesh Chanukah',
    'category': 'special',
    'name': 'שבת ראש חודש חנוכה',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Chanukah Day 1 (on Shabbat)',
    'category': 'special',
    'name': 'חנוכה - שבת ראשון',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Chanukah Day 2 (on Shabbat)',
    'category': 'special',
    'name': 'חנוכה - שבת שני',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Chanukah Day 3 (on Shabbat)',
    'category': 'special',
    'name': 'חנוכה - שבת שלישי',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Chanukah Day 4 (on Shabbat)',
    'category': 'special',
    'name': 'חנוכה - שבת רביעי',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Chanukah Day 5 (on Shabbat)',
    'category': 'special',
    'name': 'חנוכה - שבת חמישי',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Chanukah Day 7 (on Shabbat)',
    'category': 'special',
    'name': 'חנוכה - שבת שביעי',
    'ashkenaz': [
      {
        'book': 'זכריה',
        'from': '2:14',
        'to': '4:7',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Chanukah Day 8 (on Shabbat)',
    'category': 'special',
    'name': 'חנוכה - שבת שמיני',
    'ashkenaz': [
      {
        'book': 'מלכים א',
        'from': '7:40',
        'to': '7:50',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Shekalim',
    'category': 'special',
    'name': 'שבת שקלים',
    'ashkenaz': [
      {
        'book': 'מלכים ב',
        'from': '12:1',
        'to': '12:17',
      },
    ],
    'sephard': [
      {
        'book': 'מלכים ב',
        'from': '11:17',
        'to': '12:17',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Zachor',
    'category': 'special',
    'name': 'שבת זכור',
    'ashkenaz': [
      {
        'book': 'שמואל א',
        'from': '15:2',
        'to': '15:34',
      },
    ],
    'sephard': [
      {
        'book': 'שמואל א',
        'from': '15:1',
        'to': '15:34',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Parah',
    'category': 'special',
    'name': 'שבת פרה',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '36:16',
        'to': '36:38',
      },
    ],
    'sephard': [
      {
        'book': 'יחזקאל',
        'from': '36:16',
        'to': '36:36',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat HaChodesh',
    'category': 'special',
    'name': 'שבת החודש',
    'ashkenaz': [
      {
        'book': 'יחזקאל',
        'from': '45:16',
        'to': '46:18',
      },
    ],
    'sephard': [
      {
        'book': 'יחזקאל',
        'from': '45:18',
        'to': '46:15',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat HaGadol',
    'category': 'special',
    'name': 'שבת הגדול',
    'ashkenaz': [
      {
        'book': 'מלאכי',
        'from': '3:4',
        'to': '3:24',
      },
      {
        'book': 'מלאכי',
        'from': '3:23',
        'to': '3:23',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Shuva (with Vayeilech)',
    'category': 'special',
    'name': 'שבת שובה (פרשת וילך)',
    'ashkenaz': [
      {
        'book': 'הושע',
        'from': '14:2',
        'to': '14:10',
      },
      {
        'book': 'מיכה',
        'from': '7:18',
        'to': '7:20',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Shuva (with Ha\'azinu)',
    'category': 'special',
    'name': 'שבת שובה (פרשת האזינו)',
    'ashkenaz': [
      {
        'book': 'הושע',
        'from': '14:2',
        'to': '14:10',
      },
      {
        'book': 'יואל',
        'from': '2:15',
        'to': '2:27',
      },
    ],
    'sephard': [
      {
        'book': 'הושע',
        'from': '14:2',
        'to': '14:10',
      },
      {
        'book': 'מיכה',
        'from': '7:18',
        'to': '7:20',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Rosh Chodesh',
    'category': 'special',
    'name': 'שבת ראש חודש',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '66:1',
        'to': '66:24',
      },
      {
        'book': 'ישעיהו',
        'from': '66:23',
        'to': '66:23',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Rosh Chodesh Elul',
    'category': 'special',
    'name': 'שבת ראש חודש אלול',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '66:1',
        'to': '66:24',
      },
      {
        'book': 'ישעיהו',
        'from': '66:23',
        'to': '66:23',
      },
    ],
    'sephard': [
      {
        'book': 'ישעיהו',
        'from': '54:11',
        'to': '55:5',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Rosh Chodesh (Machar Chodesh)',
    'category': 'special',
    'name': 'שבת ראש חודש שני ימים (שבת וראשון)',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '66:1',
        'to': '66:24',
      },
      {
        'book': 'ישעיהו',
        'from': '66:23',
        'to': '66:23',
      },
    ],
    'sephard': [
      {
        'book': 'ישעיהו',
        'from': '66:1',
        'to': '66:24',
      },
      {
        'book': 'ישעיהו',
        'from': '66:23',
        'to': '66:23',
      },
      {
        'book': 'שמואל א',
        'from': '20:18',
        'to': '20:18',
      },
      {
        'book': 'שמואל א',
        'from': '20:42',
        'to': '20:42',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Shabbat Machar Chodesh',
    'category': 'special',
    'name': 'שבת מחר חודש',
    'ashkenaz': [
      {
        'book': 'שמואל א',
        'from': '20:18',
        'to': '20:42',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Pinchas occurring after 17 Tammuz',
    'category': 'special',
    'name': 'פנחס - כשחל אחרי י"ז תמוז',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '1:1',
        'to': '2:3',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
  {
    'id': 'h:Kedoshim following Special Shabbat',
    'category': 'special',
    'name': 'קדושים אחרי שבת מיוחדת',
    'ashkenaz': [
      {
        'book': 'עמוס',
        'from': '9:7',
        'to': '9:15',
      },
    ],
    'sephard': [
      {
        'book': 'יחזקאל',
        'from': '20:2',
        'to': '20:20',
      },
    ],
    'land': 'both',
  },
  {
    'id': 'h:Masei on Shabbat Rosh Chodesh',
    'category': 'special',
    'name': 'מסעי - בשבת ראש חודש',
    'ashkenaz': [
      {
        'book': 'ירמיהו',
        'from': '2:4',
        'to': '2:28',
      },
      {
        'book': 'ירמיהו',
        'from': '3:4',
        'to': '3:4',
      },
    ],
    'sephard': [
      {
        'book': 'ירמיהו',
        'from': '2:4',
        'to': '2:28',
      },
      {
        'book': 'ירמיהו',
        'from': '4:1',
        'to': '4:2',
      },
      {
        'book': 'ישעיהו',
        'from': '66:1',
        'to': '66:1',
      },
      {
        'book': 'ישעיהו',
        'from': '66:23',
        'to': '66:23',
      },
    ],
    'land': 'diaspora',
  },
  {
    'id': 'h:Masei on Shabbat Rosh Chodesh (Israel)',
    'category': 'special',
    'name': 'מסעי - בשבת ראש חודש',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '66:1',
        'to': '66:24',
      },
      {
        'book': 'ישעיהו',
        'from': '66:23',
        'to': '66:23',
      },
    ],
    'sephard': [
      {
        'book': 'ירמיהו',
        'from': '2:4',
        'to': '2:28',
      },
      {
        'book': 'ירמיהו',
        'from': '4:1',
        'to': '4:2',
      },
      {
        'book': 'ישעיהו',
        'from': '66:1',
        'to': '66:1',
      },
      {
        'book': 'ישעיהו',
        'from': '66:23',
        'to': '66:23',
      },
    ],
    'land': 'israel',
  },
  {
    'id': 'h:Ki Teitzei with 3rd Haftarah of Consolation',
    'category': 'special',
    'name': 'כי תצא - עם הפטרה ג\' של נחמתא',
    'ashkenaz': [
      {
        'book': 'ישעיהו',
        'from': '54:1',
        'to': '54:10',
      },
      {
        'book': 'ישעיהו',
        'from': '54:11',
        'to': '55:5',
      },
    ],
    'sephard': [],
    'land': 'both',
  },
];
