// generated by tool/tikkun_korim/generate_data.mjs — do not edit
// ignore_for_file: prefer_single_quotes

const Map<String, Object?> kTorahStructure = {
  'bereshit': {
    'name': 'בראשית',
    'parashot': [
      'בראשית',
      'נח',
      'לך לך',
      'וירא',
      'חיי שרה',
      'תולדות',
      'ויצא',
      'וישלח',
      'וישב',
      'מקץ',
      'ויגש',
      'ויחי',
    ],
  },
  'shemot': {
    'name': 'שמות',
    'parashot': [
      'שמות',
      'וארא',
      'בא',
      'בשלח',
      'יתרו',
      'משפטים',
      'תרומה',
      'תצוה',
      'כי תשא',
      'ויקהל',
      'פקודי',
    ],
  },
  'vayikra': {
    'name': 'ויקרא',
    'parashot': [
      'ויקרא',
      'צו',
      'שמיני',
      'תזריע',
      'מצורע',
      'אחרי מות',
      'קדושים',
      'אמור',
      'בהר',
      'בחוקותי',
    ],
  },
  'bamidbar': {
    'name': 'במדבר',
    'parashot': [
      'במדבר',
      'נשא',
      'בהעלותך',
      'שלח לך',
      'קרח',
      'חקת',
      'בלק',
      'פנחס',
      'מטות',
      'מסעי',
    ],
  },
  'devarim': {
    'name': 'דברים',
    'parashot': [
      'דברים',
      'ואתחנן',
      'עקב',
      'ראה',
      'שופטים',
      'כי תצא',
      'כי תבוא',
      'נצבים',
      'וילך',
      'האזינו',
      'וזאת הברכה',
    ],
  },
};

const List<String> kBooksOrder = [
  'bereshit',
  'shemot',
  'vayikra',
  'bamidbar',
  'devarim',
];

const Map<String, String> kParashaNameMapping = {
  'בחוקותי': 'בחקתי',
  'בהעלותך': 'בהעלתך',
  'שלח לך': 'שלח',
  'פנחס': 'פינחס',
};

const List<Object?> kTanachNeviim = [
  {
    'id': 'yehoshua',
    'name': 'יהושע',
    'chapters': 24,
  },
  {
    'id': 'shoftim',
    'name': 'שופטים',
    'chapters': 21,
  },
  {
    'id': 'shmuel_a',
    'name': 'שמואל א',
    'chapters': 31,
  },
  {
    'id': 'shmuel_b',
    'name': 'שמואל ב',
    'chapters': 24,
  },
  {
    'id': 'melachim_a',
    'name': 'מלכים א',
    'chapters': 22,
  },
  {
    'id': 'melachim_b',
    'name': 'מלכים ב',
    'chapters': 25,
  },
  {
    'id': 'yeshayahu',
    'name': 'ישעיהו',
    'chapters': 66,
  },
  {
    'id': 'yirmiyahu',
    'name': 'ירמיהו',
    'chapters': 52,
  },
  {
    'id': 'yechezkel',
    'name': 'יחזקאל',
    'chapters': 48,
  },
  {
    'id': 'hoshea',
    'name': 'הושע',
    'chapters': 14,
  },
  {
    'id': 'yoel',
    'name': 'יואל',
    'chapters': 4,
  },
  {
    'id': 'amos',
    'name': 'עמוס',
    'chapters': 9,
  },
  {
    'id': 'ovadia',
    'name': 'עובדיה',
    'chapters': 1,
  },
  {
    'id': 'yona',
    'name': 'יונה',
    'chapters': 4,
  },
  {
    'id': 'micha',
    'name': 'מיכה',
    'chapters': 7,
  },
  {
    'id': 'nachum',
    'name': 'נחום',
    'chapters': 3,
  },
  {
    'id': 'chavakuk',
    'name': 'חבקוק',
    'chapters': 3,
  },
  {
    'id': 'tzfania',
    'name': 'צפניה',
    'chapters': 3,
  },
  {
    'id': 'chagai',
    'name': 'חגי',
    'chapters': 2,
  },
  {
    'id': 'zecharia',
    'name': 'זכריה',
    'chapters': 14,
  },
  {
    'id': 'malachi',
    'name': 'מלאכי',
    'chapters': 3,
  },
];

const List<Object?> kTanachKetuvim = [
  {
    'id': 'tehilim',
    'name': 'תהילים',
    'chapters': 150,
  },
  {
    'id': 'mishlei',
    'name': 'משלי',
    'chapters': 31,
  },
  {
    'id': 'iyov',
    'name': 'איוב',
    'chapters': 42,
  },
  {
    'id': 'shir_hashirim',
    'name': 'שיר השירים',
    'chapters': 8,
  },
  {
    'id': 'ruth',
    'name': 'רות',
    'chapters': 4,
  },
  {
    'id': 'eicha',
    'name': 'איכה',
    'chapters': 5,
  },
  {
    'id': 'kohelet',
    'name': 'קהלת',
    'chapters': 12,
  },
  {
    'id': 'esther',
    'name': 'אסתר',
    'chapters': 10,
  },
  {
    'id': 'daniel',
    'name': 'דניאל',
    'chapters': 12,
  },
  {
    'id': 'ezra',
    'name': 'עזרא',
    'chapters': 10,
  },
  {
    'id': 'nechemia',
    'name': 'נחמיה',
    'chapters': 13,
  },
  {
    'id': 'divrei_hayamim_a',
    'name': 'דברי הימים א',
    'chapters': 29,
  },
  {
    'id': 'divrei_hayamim_b',
    'name': 'דברי הימים ב',
    'chapters': 36,
  },
];

const Map<String, String> kAliyaDisplayNames = {
  'עליה א': 'ראשון',
  'עליה ב': 'שני',
  'עליה ג': 'שלישי',
  'עליה ד': 'רביעי',
  'עליה ה': 'חמישי',
  'עליה ו': 'ששי',
  'עליה ז': 'שביעי',
  'מפטיר': 'מפטיר',
};

const Map<String, Object?> kCombinedParashaMap = {
  'ויקהל': {
    'combined': 'ויקהל-פקודי',
    'first': 'ויקהל',
  },
  'פקודי': {
    'combined': 'ויקהל-פקודי',
    'first': 'ויקהל',
  },
  'תזריע': {
    'combined': 'תזריע-מצורע',
    'first': 'תזריע',
  },
  'מצורע': {
    'combined': 'תזריע-מצורע',
    'first': 'תזריע',
  },
  'אחרי מות': {
    'combined': 'אחרי מות-קדושים',
    'first': 'אחרי מות',
  },
  'קדושים': {
    'combined': 'אחרי מות-קדושים',
    'first': 'אחרי מות',
  },
  'בהר': {
    'combined': 'בהר-בחוקותי',
    'first': 'בהר',
  },
  'בחוקותי': {
    'combined': 'בהר-בחוקותי',
    'first': 'בהר',
  },
  'בחקתי': {
    'combined': 'בהר-בחוקותי',
    'first': 'בהר',
  },
  'חקת': {
    'combined': 'חקת-בלק',
    'first': 'חקת',
  },
  'בלק': {
    'combined': 'חקת-בלק',
    'first': 'חקת',
  },
  'מטות': {
    'combined': 'מטות-מסעי',
    'first': 'מטות',
  },
  'מסעי': {
    'combined': 'מטות-מסעי',
    'first': 'מטות',
  },
  'נצבים': {
    'combined': 'נצבים-וילך',
    'first': 'נצבים',
  },
  'וילך': {
    'combined': 'נצבים-וילך',
    'first': 'נצבים',
  },
};
